
[Interface]
PrivateKey = Ym2qM9lsUi3g1T8j0enQqh2Mmrp0m+DTAwrh1OYFEwA=
Address = fdaa:33:762a:a7b:93d7:0:a:302/120
DNS = fdaa:33:762a::3

[Peer]
PublicKey = f3RKMvDcRoH44TI+SjE1ui8qTZg1gSmg1VNDsSVuXEs=
AllowedIPs = fdaa:33:762a::/48
Endpoint = sin2.gateway.6pn.dev:51820
PersistentKeepalive = 15

