-- LINE Bot 用戶對話狀態機 + 每日推播訂閱欄位
-- 2026-03-30

ALTER TABLE "LineUsers"
    ADD COLUMN IF NOT EXISTS "State"        VARCHAR(20) NOT NULL DEFAULT 'idle',
    ADD COLUMN IF NOT EXISTS "TempYear"     INTEGER,
    ADD COLUMN IF NOT EXISTS "TempMonth"    INTEGER,
    ADD COLUMN IF NOT EXISTS "TempDay"      INTEGER,
    ADD COLUMN IF NOT EXISTS "NotifyEnabled" BOOLEAN NOT NULL DEFAULT FALSE;
