-- Migration: 20260308065343_AddDailyFortune
-- 說明: 新增每日運勢快取資料表
-- 執行環境: 生產 PostgreSQL (Fly.io)

CREATE TABLE "DailyFortunes" (
    "Id"          integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId"      text NOT NULL,
    "FortuneDate" timestamp with time zone NOT NULL,
    "Content"     text NOT NULL,
    "CreatedAt"   timestamp with time zone NOT NULL,
    CONSTRAINT "PK_DailyFortunes" PRIMARY KEY ("Id")
);

-- EF Core 遷移紀錄
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260308065343_AddDailyFortune', '9.0.8');
